language: php
php:
  - '7.1'
  - '7.2'
install:
  # flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # update deps to latest in case of high deps build
  - if [ "$deps" == "high" ]; then composer config platform.php 7.2.4; composer update $flags; fi
  # install dependencies using system provided composer binary
  - composer install $flags
after_success:
  - travis_retry php vendor/bin/php-coveralls